using System;
using System.Collections.Generic;
using System.Globalization;
using System.Threading;

namespace Group2Project.Utils
{
    public static class LanguageManager
    {
        private static string _currentLanguage = "en";
        public static event Action LanguageChanged;

        public static string CurrentLanguage
        {
            get => _currentLanguage;
            set
            {
                if (_currentLanguage != value)
                {
                    _currentLanguage = value;
                    Thread.CurrentThread.CurrentUICulture = new CultureInfo(value == "zh-TW" ? "zh-TW" : "en");
                    LanguageChanged?.Invoke();
                }
            }
        }

        public static Dictionary<string, Dictionary<string, string>> Resources = new Dictionary<string, Dictionary<string, string>>
        {
            {
                "en", new Dictionary<string, string>
                {
                    { "LoginForm_Title", "CCMS - System Login" },
                    { "LoginForm_Role_Customer", "Customer" },
                    { "LoginForm_Role_Staff", "Staff" },
                    { "LoginForm_Role_Manager", "Manager" },
                    { "LoginForm_Username", "USERNAME / ID" },
                    { "LoginForm_Password_Customer", "PHONE NUMBER" },
                    { "LoginForm_Password_Staff", "PASSWORD" },
                    { "LoginForm_Show", "SHOW" },
                    { "LoginForm_Hide", "HIDE" },
                    { "LoginForm_SignIn", "SIGN IN" },
                    { "LoginForm_CantSignIn", "Can't sign in? Create an account." },
                    { "LoginForm_ForgotPassword", "Forgot password?" },
                    { "LoginForm_EnterUsernamePassword", "Please enter your Username and Password." },
                    { "LoginForm_LoginError", "Login Error" },
                    { "LoginForm_InvalidCredentials", "Invalid ID or Password. Please try again." },
                    { "LoginForm_AccessDenied", "Access Denied" },
                    { "LoginForm_InvalidCustomerCredentials", "Invalid Customer ID or Password." },
                    { "LoginForm_DatabaseError", "Database Error: " },
                    { "Language_English", "English" },
                    { "Language_Chinese", "繁體中文" },
                    { "ForgotPassword_Title", "Better Limited (Reset Password)" },
                    { "ForgotPassword_ResetTitle", "Reset Password" },
                    { "ForgotPassword_Username", "Username" },
                    { "ForgotPassword_Email", "Email Address" },
                    { "ForgotPassword_ConfirmReset", "Confirm Reset" },
                    { "ForgotPassword_EnterUsernameEmail", "Please enter both Username and Email Address." },
                    { "ForgotPassword_InputError", "Input Error" },
                    { "ForgotPassword_UserNotFound", "Account not found. Please check your username." },
                    { "ForgotPassword_EmailMismatch", "Email address does not match our records. Please check and try again." },
                    { "ForgotPassword_EmailFailed", "Failed to send email. Please try again later." },
                    { "ForgotPassword_Error", "An error occurred. Please try again later." },
                    { "ForgotPassword_NotFound", "Not Found" },
                    { "ForgotPassword_EmailMismatchTitle", "Email Mismatch" },
                    { "ForgotPassword_EmailError", "Email Error" },
                    { "ForgotPassword_SuccessTitle", "Success" },
                    { "ResetSent_Title", "Reset Password Result" },
                    { "ResetSent_EmailSent", "Email is being sent to your mail box! Please check your mail box (or Junk box also) to reset your password." },
                    { "ResetSent_Resend", "Resend Email" },
                    { "ResetSent_SignIn", "Sign In" },
                    { "ResetSent_EmailResent", "Email has been resent successfully. Please check your inbox." },
                    { "ResetSent_EmailSentTitle", "Email Sent" },
                    { "Discord_Notification_Title", "🔐 Password Reset Request" },
                    { "Discord_Notification_Username", "Username:" },
                    { "Discord_Notification_Email", "Email:" },
                    { "Discord_Notification_Time", "Time:" },
                    { "Discord_Notification_Token", "Reset Token:" },
                    { "Discord_Notification_Footer", "Please monitor this request for security purposes." },
                    { "POSForm_Title", "Point of Sale System" },
                    { "POSForm_Tab_Sales", "POS - Sales" },
                    { "POSForm_Tab_OrderHistory", "Order History" },
                    { "POSForm_Tab_DefectReport", "Defect Report" },
                    { "POSForm_SearchTitle", "Product Search" },
                    { "POSForm_ProductId", "Product ID:" },
                    { "POSForm_Category", "Category:" },
                    { "POSForm_PriceRange", "Price Range:" },
                    { "POSForm_Min", "Min:" },
                    { "POSForm_Max", "Max:" },
                    { "POSForm_Barcode", "Barcode:" },
                    { "POSForm_Description", "Description:" },
                    { "POSForm_Search", "Search" },
                    { "POSForm_SearchResults", "Search Results" },
                    { "POSForm_AddToCart", "Add to Cart" },
                    { "POSForm_CartTitle", "Shopping Cart" },
                    { "POSForm_Subtotal", "Subtotal:" },
                    { "POSForm_Discount", "Discount:" },
                    { "POSForm_Tax", "Tax:" },
                    { "POSForm_Total", "Total:" },
                    { "POSForm_ClearCart", "Clear Cart" },
                    { "POSForm_Checkout", "Checkout" },
                    { "POSForm_EnterQuantity", "Enter Quantity" },
                    { "POSForm_Quantity", "Quantity:" },
                    { "POSForm_OK", "OK" },
                    { "POSForm_Cancel", "Cancel" },
                    { "POSForm_CartEmpty", "Cart is empty!" },
                    { "POSForm_Warning", "Warning" },
                    { "POSForm_Error", "Error" },
                    { "POSForm_Success", "Success" },
                    { "POSForm_ClearCartConfirm", "Clear entire cart?" },
                    { "POSForm_RemoveItemConfirm", "Remove this item from cart?" },
                    { "POSForm_Confirm", "Confirm" },
                    { "POSForm_OutOfStock", "Product is out of stock!" },
                    { "POSForm_InvalidQuantity", "Invalid quantity or insufficient stock!" },
                    { "POSForm_CheckoutComplete", "Checkout completed successfully!" },
                    { "POSForm_CheckoutError", "Checkout error: " },
                    { "POSForm_LoadProductsError", "Error loading products: " },
                    { "POSForm_SearchProductsError", "Error searching products: " },
                    { "POSForm_AddToCartError", "Error adding to cart: " },
                    { "POSForm_FoundProducts", "Found {0} products" },
                    { "POSForm_AddedToCart", "Added {0} x {1} to cart" },
                    { "POSForm_CartCleared", "Cart cleared" },
                    { "CheckoutForm_Title", "Checkout" },
                    { "CheckoutForm_Cart", "Shopping Cart" },
                    { "CheckoutForm_PaymentMethod", "Payment Method" },
                    { "CheckoutForm_Total", "Total:" },
                    { "CheckoutForm_Discount", "Discount:" },
                    { "CheckoutForm_PaidAmount", "Paid Amount:" },
                    { "CheckoutForm_PrintReceipt", "Print Receipt" },
                    { "CheckoutForm_DeliveryOptions", "Delivery Options" },
                    { "CheckoutForm_RequireDelivery", "Require Delivery & Installation" },
                    { "CheckoutForm_Address", "Address:" },
                    { "CheckoutForm_Contact", "Contact Number:" },
                    { "CheckoutForm_DeliveryDate", "Delivery Date:" },
                    { "CheckoutForm_InstallationTime", "Installation Time:" },
                    { "CheckoutForm_Morning", "Morning (9AM - 12PM)" },
                    { "CheckoutForm_Afternoon", "Afternoon (12PM - 5PM)" },
                    { "CheckoutForm_Evening", "Evening (5PM - 8PM)" },
                    { "CheckoutForm_ConfirmOrder", "Confirm Order" },
                    { "CheckoutForm_Cancel", "Cancel" },
                    { "CheckoutForm_SelectPayment", "Please select a payment method!" },
                    { "CheckoutForm_ValidPaidAmount", "Please enter a valid paid amount!" },
                    { "CheckoutForm_FillDelivery", "Please fill in delivery details!" },
                    { "OrderHistory_Title", "Order History" },
                    { "OrderHistory_Search", "Search" },
                    { "OrderHistory_Refresh", "Refresh" },
                    { "OrderHistory_ViewDetails", "View Details" },
                    { "OrderHistory_CancelOrder", "Cancel Order" },
                    { "OrderHistory_DeleteOrder", "Delete Order" },
                    { "OrderHistory_OrderId", "Order ID" },
                    { "OrderHistory_CustomerName", "Customer Name" },
                    { "OrderHistory_Contact", "Contact" },
                    { "OrderHistory_OrderDate", "Order Date" },
                    { "OrderHistory_TotalAmount", "Total Amount" },
                    { "OrderHistory_Status", "Status" },
                    { "OrderHistory_SearchOrdersError", "Error searching orders: " },
                    { "OrderHistory_LoadDetailsError", "Error loading details: " },
                    { "OrderHistory_DeleteOrderError", "Error deleting order: " },
                    { "OrderHistory_CancelConfirm", "Cancel this order?" },
                    { "OrderHistory_DeleteConfirm", "Delete this order? This cannot be undone!" },
                    { "OrderHistory_OrderCanceled", "Order canceled!" },
                    { "OrderHistory_OrderDeleted", "Order deleted!" },
                    { "OrderHistory_OrderDetails", "Order Details" },
                    { "DefectReport_Title", "Report Defective Item" },
                    { "DefectReport_ProductId", "Product ID:" },
                    { "DefectReport_ProductName", "Product Name:" },
                    { "DefectReport_Description", "Defect Description:" },
                    { "DefectReport_Submit", "Submit Report" },
                    { "DefectReport_FillFields", "Please fill in all fields!" },
                    { "DefectReport_SubmitSuccess", "Defect report submitted successfully!" },
                    { "DefectReport_SubmitError", "Error submitting defect report: " },
                    { "Receipt_Title", "PREMIUM LIVING FURNITURE" },
                    { "Receipt_Subtitle", "Official Sales Receipt" },
                    { "Receipt_OrderId", "Order ID:" },
                    { "Receipt_Date", "Date:" },
                    { "Receipt_PaymentMethod", "Payment Method:" },
                    { "Receipt_Quantity", "Qty" },
                    { "Receipt_ItemDescription", "Item Description" },
                    { "Receipt_UnitPrice", "Unit Price" },
                    { "Receipt_Subtotal", "Subtotal" },
                    { "Receipt_Total", "Total" },
                    { "Receipt_Paid", "Paid" },
                    { "Receipt_ThankYou", "Thank you for your business!" },
                    { "Receipt_Warranty", "Please contact our After-Sales department for any warranty claims." },
                    { "InventoryForm_Title", "Inventory Management" },
                    { "InventoryForm_Tab_MultiLocation", "Multi-Location Inventory" },
                    { "InventoryForm_Tab_Restock", "Restock Requests" },
                    { "InventoryForm_Tab_StockMovements", "Stock Movements" },
                    { "InventoryForm_Tab_Quotation", "Quotation & Delivery" },
                    { "InventoryForm_Location", "Location:" },
                    { "InventoryForm_RefreshStock", "Refresh Stock" },
                    { "InventoryForm_CheckLowStock", "Check Low Stock & Auto Restock" },
                    { "InventoryForm_RecordOutward", "Record Outward (Outbound)" },
                    { "InventoryForm_ItemId", "Item ID:" },
                    { "InventoryForm_Quantity", "Quantity:" },
                    { "InventoryForm_Reference", "Reference:" },
                    { "InventoryForm_Notes", "Notes:" },
                    { "InventoryForm_InventoryByLocation", "Inventory by Location" },
                    { "InventoryForm_SwitchLocation", "Switch between locations (e.g., Main Warehouse, Kowloon Bay Retail Shop) to manage stock." },
                    { "InventoryForm_QuotationDelivery", "Warehouse Quotation & Dispatch Proofs" },
                    { "InventoryForm_GenerateQuotation", "Generate official quotations for walk-in transactions or delivery notes for logistics verification." },
                    { "InventoryForm_PrintQuotation", "Print Quotation / Delivery Note" },
                    { "InventoryForm_VerifyStock", "Verify Stock & Send to Logistics" },
                    { "InventoryForm_SelectOrder", "Please select an order to generate the quotation." },
                    { "InventoryForm_TermsConditions", "Terms & Conditions:" },
                    { "InventoryForm_DocPurpose", "This document serves as a quotation and inventory dispatch proof." },
                    { "InventoryForm_WalkIn", "For walk-in customers, this validates on-site goods receipt." },
                    { "InventoryForm_ReportDiscrepancy", "Any stock discrepancies must be reported within 24 hours." },
                    { "InventoryForm_WarehouseAuth", "Warehouse Authorized Signature:" },
                    { "InventoryForm_CustomerDriver", "Customer / Driver Signature:" },
                    { "InventoryForm_ConfirmVerify", "Have you verified the physical stock for Order {orderId}?\n\nClicking 'Yes' will mark it as Ready and push it directly to Logistics for delivery scheduling." },
                    { "InventoryForm_VerifyStockDispatch", "Verify Stock & Dispatch" },
                    { "InventoryForm_RestockApproval", "Restock Request Approval Workflow" },
                    { "InventoryForm_ThreeLevelApproval", "Three-level approval: Shop Manager → Inventory Manager → Purchase Department" },
                    { "InventoryForm_FilterLocation", "Filter by Location:" },
                    { "InventoryForm_Refresh", "Refresh" },
                    { "InventoryForm_Approve", "Approve (Next Level)" },
                    { "InventoryForm_Reject", "Reject Request" },
                    { "InventoryForm_SelectRequest", "Please select a restock request to approve." },
                    { "InventoryForm_SelectReject", "Please select a restock request to reject." },
                    { "InventoryForm_CannotApprove", "This request is '{status}' and cannot be approved further." },
                    { "InventoryForm_CannotReject", "This request is '{status}' and cannot be rejected." },
                    { "InventoryForm_ConfirmApprove", "Approve Restock Request #{restockId} as {role}?\n\nThis will advance the approval to the next level." },
                    { "InventoryForm_ConfirmReject", "Reject Restock Request #{restockId}?\n\nThis will permanently reject the request." },
                    { "InventoryForm_StockMovements", "Stock Movements (Inbound & Outbound)" },
                    { "InventoryForm_StockMovementsDesc", "Track all inventory movements for audit trail and accuracy verification." },
                    { "InventoryForm_FilterProduct", "Filter by Product:" },
                    { "InventoryForm_StockListRefreshed", "Stock list refreshed." },
                    { "InventoryForm_PleaseFillItemIdQty", "Please fill in both Item ID and Quantity." },
                    { "InventoryForm_PleaseValidQty", "Quantity must be a valid positive number." },
                    { "InventoryForm_StockIncreased", "Stock for Item {id} increased by {qty}!" },
                    { "InventoryForm_ProcurementListRefreshed", "Procurement list refreshed." },
                    { "InventoryForm_PleaseSelectSupplierItem", "Please select a Supplier and a Material Item." },
                    { "InventoryForm_PleaseValidEstCost", "Estimated Cost must be a valid positive number." },
                    { "InventoryForm_ProcurementCreated", "Procurement order created successfully!" },
                    { "InventoryForm_SelectProcurementCancel", "Please select a procurement order to cancel." },
                    { "InventoryForm_AlreadyCanceled", "This order is already canceled!" },
                    { "InventoryForm_ConfirmCancelProcurement", "Are you sure you want to cancel Procurement ID: {procId}?" },
                    { "InventoryForm_ProcurementCanceled", "Procurement order {procId} canceled." },
                    { "InventoryForm_SelectProcurementEdit", "Please select a procurement order to edit." },
                    { "InventoryForm_EditMode", "Entering Edit Mode for Procurement ID: {procId}.\n\n(System Note: Full modification interface is scheduled for next update.)" },
                    { "InventoryForm_SelectProcurementUpdate", "Please select a procurement order to update its status." },
                    { "InventoryForm_WaitApproval", "This order is still 'Pending'. You must wait for the Finance Department to APPROVE it before ordering." },
                    { "InventoryForm_AlreadyReceived", "This order has already been 'Received' and is completed." },
                    { "InventoryForm_AdvanceProcurement", "Advance Procurement ID: {procId}\n\nFrom: [{currentStatus}]\nTo: [{nextStatus}]?" },
                    { "InventoryForm_ConfirmProgress", "Confirm Progress" },
                    { "InventoryForm_ProcurementAdvanced", "Procurement {procId} advanced to '{nextStatus}'." },
                    { "InventoryForm_QuotationRefreshed", "Quotation list refreshed." },
                    { "InventoryForm_QuotationPrinted", "Quotation printed successfully!" },
                    { "InventoryForm_OrderSentLogistics", "Order {orderId} is packed and sent to Logistics!" },
                    { "InventoryForm_LowStockCheckComplete", "Low stock check completed. Restock requests auto-generated!" },
                    { "InventoryForm_OutwardRecorded", "Outbound recorded: Item {id}, Qty {qty}, from {loc}!" },
                    { "PurchaseForm_Title", "Purchase Management" },
                    { "PurchaseForm_Tab_Orders", "Purchase Orders" },
                    { "PurchaseForm_Tab_Suppliers", "Suppliers" },
                    { "PurchaseForm_Tab_Products", "Products" },
                    { "PurchaseForm_CreatePO", "Create Purchase Order" },
                    { "PurchaseForm_ApprovePO", "Approve Purchase Order" },
                    { "PurchaseForm_CancelPO", "Cancel Purchase Order" },
                    { "PurchaseForm_PrintPO", "Print Purchase Order" },
                    { "PurchaseForm_Refresh", "Refresh" },
                    { "PurchaseForm_PO_ID", "PO ID" },
                    { "PurchaseForm_Supplier", "Supplier" },
                    { "PurchaseForm_TotalAmount", "Total Amount" },
                    { "PurchaseForm_Status", "Status" },
                    { "PurchaseForm_Date", "Date" },
                    { "PurchaseForm_CreatedBy", "Created By" },
                    { "PurchaseForm_Notes", "Notes" },
                    { "PurchaseForm_Product_ID", "Product ID" },
                    { "PurchaseForm_Product_Name", "Product Name" },
                    { "PurchaseForm_Quantity", "Quantity" },
                    { "PurchaseForm_UnitPrice", "Unit Price" },
                    { "PurchaseForm_LineTotal", "Line Total" },
                    { "PurchaseForm_PleaseSelectPO", "Please select a purchase order first." },
                    { "PurchaseForm_CreatedSuccess", "Purchase Order created successfully!" },
                    { "PurchaseForm_ApprovedSuccess", "Purchase Order approved successfully!" },
                    { "PurchaseForm_CancelledSuccess", "Purchase Order cancelled successfully!" },
                    { "PurchaseForm_Status_PendingAccounting", "Pending Accounting Approval" },
                    { "PurchaseForm_Status_PendingApproval", "Pending Approval" },
                    { "PurchaseForm_Status_Approved", "Approved" },
                    { "PurchaseForm_Status_SentToSupplier", "Sent to Supplier" },
                    { "PurchaseForm_Status_Received", "Received" },
                    { "PurchaseForm_Status_Cancelled", "Cancelled" },
                    { "MasterDataForm_Title", "Master Data Management" },
                    { "MasterDataForm_Tab_Staff", "Staff" },
                    { "MasterDataForm_Tab_Suppliers", "Suppliers" },
                    { "MasterDataForm_Tab_Customers", "Customers" },
                    { "MasterDataForm_Tab_Drivers", "Drivers" },
                    { "MasterDataForm_Tab_Products", "Products" },
                    { "MasterDataForm_Add", "Add" },
                    { "MasterDataForm_Edit", "Edit" },
                    { "MasterDataForm_Delete", "Delete" },
                    { "MasterDataForm_Refresh", "Refresh" },
                    { "MasterDataForm_ExportPDF", "Export PDF" },
                    { "MasterDataForm_SupplierID", "Supplier ID" },
                    { "MasterDataForm_SupplierName", "Company Name" },
                    { "MasterDataForm_ContactPerson", "Contact Person" },
                    { "MasterDataForm_ContactNumber", "Contact Number" },
                    { "MasterDataForm_Address", "Address" },
                    { "MasterDataForm_SupplierStatus", "Status" },
                    { "MasterDataForm_ProductID", "Product ID" },
                    { "MasterDataForm_ProductName", "Product Name" },
                    { "MasterDataForm_Category", "Category" },
                    { "MasterDataForm_UnitPrice", "Unit Price" },
                    { "MasterDataForm_PurchasePrice", "Purchase Price" },
                    { "MasterDataForm_Description", "Description" },
                    { "MasterDataForm_ProductStatus", "Status" },
                    { "MasterDataForm_PleaseFillDetails", "Please fill in all required details." },
                    { "MasterDataForm_SupplierAdded", "Supplier added successfully!" },
                    { "MasterDataForm_SupplierUpdated", "Supplier updated successfully!" },
                    { "MasterDataForm_SupplierDeleted", "Supplier deleted successfully!" },
                    { "MasterDataForm_ProductAdded", "Product added successfully!" },
                    { "MasterDataForm_ProductUpdated", "Product updated successfully!" },
                    { "MasterDataForm_ProductDeleted", "Product deleted successfully!" },
                    { "MasterDataForm_ConfirmDelete", "Are you sure you want to delete this?" },
                    { "LogisticForm_Title", "Shipping & Logistics" },
                    { "LogisticForm_Tab_Pending", "Pending Deliveries" },
                    { "LogisticForm_Tab_Scheduling", "Scheduling Dashboard" },
                    { "LogisticForm_Tab_Tracking", "Shipment Tracking" },
                    { "LogisticForm_Filter_Today", "Today" },
                    { "LogisticForm_Filter_Tomorrow", "Tomorrow" },
                    { "LogisticForm_Filter_Custom", "Custom Date" },
                    { "LogisticForm_Unassigned_List", "Unassigned Deliveries" },
                    { "LogisticForm_Assign_Team", "Assign to Team" },
                    { "LogisticForm_Team_Workload", "Team Workload" },
                    { "LogisticForm_Select_Delivery", "Please select deliveries to assign." },
                    { "LogisticForm_Select_Team", "Please select a team to assign." },
                    { "LogisticForm_Assign_Success", "{count} deliveries assigned to {team} successfully!" },
                    { "LogisticForm_Refresh", "Refresh" },
                    { "LogisticForm_Delivery_ID", "Delivery ID" },
                    { "LogisticForm_Order_Ref", "Order Ref." },
                    { "LogisticForm_Customer", "Customer" },
                    { "LogisticForm_Phone", "Phone" },
                    { "LogisticForm_Address", "Address" },
                    { "LogisticForm_Volume", "Volume" },
                    { "LogisticForm_Installation", "Installation" },
                    { "LogisticForm_Assigned_Team", "Assigned Team" },
                    { "LogisticForm_Scheduled_Date", "Scheduled Date" },
                    { "LogisticForm_Created_On", "Created On" },
                    { "LogisticForm_Team_ID", "Team ID" },
                    { "LogisticForm_Team_Name", "Team Name" },
                    { "LogisticForm_Team_Type", "Team Type" },
                    { "LogisticForm_Members", "Members" },
                    { "LogisticForm_Time_Slot", "Time Slot" },
                    { "LogisticForm_Status", "Status" },
                    { "HRForm_Title", "HR & User Management" },
                    { "HRForm_Tab_Staff", "Staff Directory" },
                    { "HRForm_Tab_Roles", "Roles & Permissions" },
                    { "HRForm_Add_Staff", "Add Staff" },
                    { "HRForm_Update_Staff", "Update Staff Profile" },
                    { "HRForm_Search_Placeholder", "Search staff by ID, name, or department..." },
                    { "HRForm_Department", "Department" },
                    { "HRForm_Job_Title", "Job Title" },
                    { "HRForm_Location", "Location" },
                    { "HRForm_Role", "System Role" },
                    { "HRForm_Phone", "Phone" },
                    { "HRForm_Email", "Email" },
                    { "HRForm_Hire_Date", "Hire Date" },
                    { "HRForm_Staff_Status", "Status" },
                    { "HRForm_Password", "Password" },
                    { "HRForm_Confirm_Password", "Confirm Password" },
                    { "HRForm_New_Password", "New Password" },
                    { "HRForm_Password_Strength", "Password Strength" },
                    { "HRForm_Password_Invalid", "Password does not meet security requirements" },
                    { "HRForm_Passwords_Do_Not_Match", "Passwords do not match" },
                    { "HRForm_Select_Department_First", "Please select a department first" },
                    { "HRForm_Location_Required", "Please assign a location (Retail Shop, Warehouse, or Team)" },
                    { "HRForm_Staff_Added", "Staff added successfully!" },
                    { "HRForm_Staff_Updated", "Staff profile updated successfully!" },
                    { "HRForm_Staff_Deleted", "Staff deleted successfully!" },
                    { "HRForm_Confirm_Delete", "Are you sure you want to delete this staff member?" },
                    { "HRForm_Select_Staff", "Please select a staff member" },
                    { "HRForm_Staff_ID", "Staff ID" },
                    { "HRForm_Staff_Name", "Staff Name" },
                    { "Dashboard_Title", "Executive Dashboard" },
                    { "Dashboard_TotalOrders", "Total Orders" },
                    { "Dashboard_TotalSoldItems", "Total Sold Items" },
                    { "Dashboard_TotalRevenue", "Total Revenue" },
                    { "Dashboard_TotalGrossProfit", "Total Gross Profit" },
                    { "Dashboard_7DayTrend", "7-Day Order Trend" },
                    { "Dashboard_TopSellingProducts", "Top Selling Products" },
                    { "Dashboard_CurrentMonth", "Current Month" },
                    { "HRForm_Department_Admin", "Administration" },
                    { "HRForm_Department_Sales", "Sales" },
                    { "HRForm_Department_Tech", "Technical" },
                    { "HRForm_Department_Logistics", "Logistics" },
                    { "HRForm_Department_Warehouse", "Warehouse" },
                    { "HRForm_Location_HQ", "Headquarters" },
                    { "HRForm_Location_Retail_Shop", "Retail Shop" },
                    { "HRForm_Location_Warehouse", "Warehouse" },
                    { "HRForm_Location_Delivery_Team", "Delivery Team" },
                    { "HRForm_Location_Tech_Team", "Technical Team" },
                    { "HRForm_Role_Admin", "Administrator" },
                    { "HRForm_Role_Manager", "Manager" },
                    { "HRForm_Role_Staff", "Staff" },
                    { "HRForm_Status_Active", "Active" },
                    { "HRForm_Status_Inactive", "Inactive" },
                    { "MessageForm_Title", "Internal Mailbox" },
                    { "MessageForm_Tab_Inbox", "Inbox" },
                    { "MessageForm_Tab_Outbox", "Sent Items" },
                    { "MessageForm_Btn_Unread_Filter", "Unread Only" },
                    { "MessageForm_Btn_Show_All", "Show All" },
                    { "MessageForm_Btn_Send_Message", "Send Message" },
                    { "MessageForm_Btn_Refresh", "Refresh" },
                    { "MessageForm_Btn_Mark_Read", "Mark Read" },
                    { "MessageForm_Btn_Delete", "Delete" },
                    { "MessageForm_Btn_Reply", "Reply" },
                    { "MessageForm_Lbl_Recipient", "To:" },
                    { "MessageForm_Lbl_Subject", "Subject:" },
                    { "MessageForm_Lbl_Content", "Content:" },
                    { "MessageForm_Please_Fill_All", "Please fill all information!" },
                    { "MessageForm_Message_Sent", "Message sent successfully!" },
                    { "MessageForm_Confirm_Delete", "Are you sure you want to delete this message?" },
                    { "NotificationForm_Title", "System Notifications" },
                    { "NotificationForm_Btn_Unread_Filter", "Unread Only" },
                    { "NotificationForm_Btn_Show_All", "Show All" },
                    { "NotificationForm_Btn_Refresh", "Refresh" },
                    { "NotificationForm_Btn_Mark_All_Read", "Mark All Read" },
                    { "NotificationForm_Btn_Clear_All", "Clear All" },
                    { "NotificationForm_Btn_Test_Notification", "Test Notification" },
                    { "NotificationForm_All_Marked_Read", "All marked as read!" },
                    { "NotificationForm_Confirm_Clear_All", "Are you sure you want to clear all notifications?" },
                    { "NotificationForm_Test_Title", "Test Notification" },
                    { "NotificationForm_Test_Message", "This is a Windows Balloon Notification test!" },
                    { "NotificationType_New_Message", "New Message" },
                    { "NotificationType_Restock_Approval", "Restock Request" },
                    { "NotificationType_Purchase_Approval", "Purchase Request" },
                    { "NotificationType_System_Alert", "System Alert" },
                    { "NotificationType_Urgent_Task", "Urgent Task" },
                    { "MainForm_Logout", "Log Out" },
                    { "MainForm_LogoutConfirm", "Are you sure you want to log out?" },
                    { "MainForm_LogoutConfirmTitle", "Confirm Logout" }
                }
            },
            {
                "zh-TW", new Dictionary<string, string>
                {
                    { "LoginForm_Title", "CCMS - 系統登入" },
                    { "LoginForm_Role_Customer", "客戶" },
                    { "LoginForm_Role_Staff", "員工" },
                    { "LoginForm_Role_Manager", "經理" },
                    { "LoginForm_Username", "用戶名 / ID" },
                    { "LoginForm_Password_Customer", "電話號碼" },
                    { "LoginForm_Password_Staff", "密碼" },
                    { "LoginForm_Show", "顯示" },
                    { "LoginForm_Hide", "隱藏" },
                    { "LoginForm_SignIn", "登入" },
                    { "LoginForm_CantSignIn", "無法登入？建立帳戶。" },
                    { "LoginForm_ForgotPassword", "忘記密碼？" },
                    { "LoginForm_EnterUsernamePassword", "請輸入用戶名和密碼。" },
                    { "LoginForm_LoginError", "登入錯誤" },
                    { "LoginForm_InvalidCredentials", "無效的ID或密碼。請重試。" },
                    { "LoginForm_AccessDenied", "存取被拒" },
                    { "LoginForm_InvalidCustomerCredentials", "無效的客戶ID或密碼。" },
                    { "LoginForm_DatabaseError", "資料庫錯誤：" },
                    { "Language_English", "English" },
                    { "Language_Chinese", "繁體中文" },
                    { "ForgotPassword_Title", "Better Limited (重置密碼)" },
                    { "ForgotPassword_ResetTitle", "重置密碼" },
                    { "ForgotPassword_Username", "用戶名" },
                    { "ForgotPassword_Email", "電子郵件" },
                    { "ForgotPassword_ConfirmReset", "確認重置" },
                    { "ForgotPassword_EnterUsernameEmail", "請輸入用戶名和電子郵件。" },
                    { "ForgotPassword_InputError", "輸入錯誤" },
                    { "ForgotPassword_UserNotFound", "找不到帳戶。請檢查您的用戶名。" },
                    { "ForgotPassword_EmailMismatch", "電子郵件與我們的記錄不符。請檢查並重試。" },
                    { "ForgotPassword_EmailFailed", "發送郵件失敗。請稍後重試。" },
                    { "ForgotPassword_Error", "發生錯誤。請稍後重試。" },
                    { "ForgotPassword_NotFound", "找不到" },
                    { "ForgotPassword_EmailMismatchTitle", "電子郵件不符" },
                    { "ForgotPassword_EmailError", "郵件錯誤" },
                    { "ForgotPassword_SuccessTitle", "成功" },
                    { "ResetSent_Title", "重置密碼結果" },
                    { "ResetSent_EmailSent", "郵件正在發送到您的郵箱！請檢查您的郵箱（或垃圾郵件箱）以重置密碼。" },
                    { "ResetSent_Resend", "重新發送郵件" },
                    { "ResetSent_SignIn", "登入" },
                    { "ResetSent_EmailResent", "郵件已成功重新發送。請檢查您的收件箱。" },
                    { "ResetSent_EmailSentTitle", "郵件已發送" },
                    { "Discord_Notification_Title", "🔐 密碼重置請求" },
                    { "Discord_Notification_Username", "用戶名：" },
                    { "Discord_Notification_Email", "電子郵件：" },
                    { "Discord_Notification_Time", "時間：" },
                    { "Discord_Notification_Token", "重置令牌：" },
                    { "Discord_Notification_Footer", "出於安全目的，請監控此請求。" },
                    { "POSForm_Title", "銷售點系統" },
                    { "POSForm_Tab_Sales", "POS - 銷售" },
                    { "POSForm_Tab_OrderHistory", "訂單歷史" },
                    { "POSForm_Tab_DefectReport", "瑕疵報告" },
                    { "POSForm_SearchTitle", "商品搜尋" },
                    { "POSForm_ProductId", "商品編號：" },
                    { "POSForm_Category", "商品分類：" },
                    { "POSForm_PriceRange", "價格範圍：" },
                    { "POSForm_Min", "最低：" },
                    { "POSForm_Max", "最高：" },
                    { "POSForm_Barcode", "條碼：" },
                    { "POSForm_Description", "商品描述：" },
                    { "POSForm_Search", "搜尋" },
                    { "POSForm_SearchResults", "搜尋結果" },
                    { "POSForm_AddToCart", "加入購物車" },
                    { "POSForm_CartTitle", "購物車" },
                    { "POSForm_Subtotal", "小計：" },
                    { "POSForm_Discount", "折扣：" },
                    { "POSForm_Tax", "稅金：" },
                    { "POSForm_Total", "總計：" },
                    { "POSForm_ClearCart", "清空購物車" },
                    { "POSForm_Checkout", "結帳" },
                    { "POSForm_EnterQuantity", "輸入數量" },
                    { "POSForm_Quantity", "數量：" },
                    { "POSForm_OK", "確定" },
                    { "POSForm_Cancel", "取消" },
                    { "POSForm_CartEmpty", "購物車是空的！" },
                    { "POSForm_Warning", "警告" },
                    { "POSForm_Error", "錯誤" },
                    { "POSForm_Success", "成功" },
                    { "POSForm_ClearCartConfirm", "確定要清空購物車嗎？" },
                    { "POSForm_RemoveItemConfirm", "確定要從購物車中移除這個項目嗎？" },
                    { "POSForm_Confirm", "確認" },
                    { "POSForm_OutOfStock", "商品缺貨！" },
                    { "POSForm_InvalidQuantity", "無效的數量或庫存不足！" },
                    { "POSForm_CheckoutComplete", "結帳成功完成！" },
                    { "POSForm_CheckoutError", "結帳錯誤：" },
                    { "POSForm_LoadProductsError", "載入商品錯誤：" },
                    { "POSForm_SearchProductsError", "搜尋商品錯誤：" },
                    { "POSForm_AddToCartError", "加入購物車錯誤：" },
                    { "POSForm_FoundProducts", "找到 {0} 個商品" },
                    { "POSForm_AddedToCart", "已加入 {0} x {1} 到購物車" },
                    { "POSForm_CartCleared", "購物車已清空" },
                    { "CheckoutForm_Title", "結帳" },
                    { "CheckoutForm_Cart", "購物車" },
                    { "CheckoutForm_PaymentMethod", "付款方式" },
                    { "CheckoutForm_Total", "總計：" },
                    { "CheckoutForm_Discount", "折扣：" },
                    { "CheckoutForm_PaidAmount", "付款金額：" },
                    { "CheckoutForm_PrintReceipt", "列印收據" },
                    { "CheckoutForm_DeliveryOptions", "送貨選項" },
                    { "CheckoutForm_RequireDelivery", "需要送貨與安裝" },
                    { "CheckoutForm_Address", "地址：" },
                    { "CheckoutForm_Contact", "聯絡電話：" },
                    { "CheckoutForm_DeliveryDate", "送貨日期：" },
                    { "CheckoutForm_InstallationTime", "安裝時間：" },
                    { "CheckoutForm_Morning", "上午 (9AM - 12PM)" },
                    { "CheckoutForm_Afternoon", "下午 (12PM - 5PM)" },
                    { "CheckoutForm_Evening", "晚上 (5PM - 8PM)" },
                    { "CheckoutForm_ConfirmOrder", "確認訂單" },
                    { "CheckoutForm_Cancel", "取消" },
                    { "CheckoutForm_SelectPayment", "請選擇付款方式！" },
                    { "CheckoutForm_ValidPaidAmount", "請輸入有效的付款金額！" },
                    { "CheckoutForm_FillDelivery", "請填寫送貨詳情！" },
                    { "OrderHistory_Title", "訂單歷史" },
                    { "OrderHistory_Search", "搜尋" },
                    { "OrderHistory_Refresh", "重新整理" },
                    { "OrderHistory_ViewDetails", "檢視詳情" },
                    { "OrderHistory_CancelOrder", "取消訂單" },
                    { "OrderHistory_DeleteOrder", "刪除訂單" },
                    { "OrderHistory_OrderId", "訂單編號" },
                    { "OrderHistory_CustomerName", "客戶名稱" },
                    { "OrderHistory_Contact", "聯絡方式" },
                    { "OrderHistory_OrderDate", "訂單日期" },
                    { "OrderHistory_TotalAmount", "總金額" },
                    { "OrderHistory_Status", "狀態" },
                    { "OrderHistory_SearchOrdersError", "搜尋訂單錯誤：" },
                    { "OrderHistory_LoadDetailsError", "載入詳情錯誤：" },
                    { "OrderHistory_DeleteOrderError", "刪除訂單錯誤：" },
                    { "OrderHistory_CancelConfirm", "確定要取消這個訂單嗎？" },
                    { "OrderHistory_DeleteConfirm", "確定要刪除這個訂單嗎？此動作無法復原！" },
                    { "OrderHistory_OrderCanceled", "訂單已取消！" },
                    { "OrderHistory_OrderDeleted", "訂單已刪除！" },
                    { "OrderHistory_OrderDetails", "訂單詳情" },
                    { "DefectReport_Title", "瑕疵商品回報" },
                    { "DefectReport_ProductId", "商品編號：" },
                    { "DefectReport_ProductName", "商品名稱：" },
                    { "DefectReport_Description", "瑕疵描述：" },
                    { "DefectReport_Submit", "提交報告" },
                    { "DefectReport_FillFields", "請填寫所有欄位！" },
                    { "DefectReport_SubmitSuccess", "瑕疵報告提交成功！" },
                    { "DefectReport_SubmitError", "提交瑕疵報告錯誤：" },
                    { "Receipt_Title", "高級生活家具" },
                    { "Receipt_Subtitle", "正式銷售收據" },
                    { "Receipt_OrderId", "訂單編號：" },
                    { "Receipt_Date", "日期：" },
                    { "Receipt_PaymentMethod", "付款方式：" },
                    { "Receipt_Quantity", "數量" },
                    { "Receipt_ItemDescription", "商品描述" },
                    { "Receipt_UnitPrice", "單價" },
                    { "Receipt_Subtotal", "小計" },
                    { "Receipt_Total", "總計" },
                    { "Receipt_Paid", "已付" },
                    { "Receipt_ThankYou", "感謝您的惠顧！" },
                    { "Receipt_Warranty", "如有任何保固問題，請聯絡我們的售後部門。" },
                    { "InventoryForm_Title", "庫存管理" },
                    { "InventoryForm_Tab_MultiLocation", "跨據點庫存" },
                    { "InventoryForm_Tab_Restock", "補貨申請" },
                    { "InventoryForm_Tab_StockMovements", "庫存流轉" },
                    { "InventoryForm_Tab_Quotation", "報價單 & 出貨" },
                    { "InventoryForm_Location", "據點：" },
                    { "InventoryForm_RefreshStock", "重新整理庫存" },
                    { "InventoryForm_CheckLowStock", "檢查低庫存並自動補貨" },
                    { "InventoryForm_RecordOutward", "記錄出庫" },
                    { "InventoryForm_ItemId", "商品編號：" },
                    { "InventoryForm_Quantity", "數量：" },
                    { "InventoryForm_Reference", "參考：" },
                    { "InventoryForm_Notes", "備註：" },
                    { "InventoryForm_InventoryByLocation", "據點庫存" },
                    { "InventoryForm_SwitchLocation", "切換不同據點（如總倉庫、九龍灣門市等來管理庫存。" },
                    { "InventoryForm_QuotationDelivery", "倉庫報價單 & 出貨證明" },
                    { "InventoryForm_GenerateQuotation", "為現場交易產生正式報價單，或為物流驗證產生出貨證明。" },
                    { "InventoryForm_PrintQuotation", "列印報價單 / 出貨證明" },
                    { "InventoryForm_VerifyStock", "驗證庫存並發送至物流" },
                    { "InventoryForm_SelectOrder", "請選擇一個訂單來產生報價單。" },
                    { "InventoryForm_TermsConditions", "條款與條件：" },
                    { "InventoryForm_DocPurpose", "本文件作為報價單及庫存出貨證明。" },
                    { "InventoryForm_WalkIn", "對於現場客戶，這可作為現場商品驗收證明。" },
                    { "InventoryForm_ReportDiscrepancy", "任何庫存差異必須在24小時內報告。" },
                    { "InventoryForm_WarehouseAuth", "倉庫授權簽名：" },
                    { "InventoryForm_CustomerDriver", "客戶 / 司機簽名：" },
                    { "InventoryForm_ConfirmVerify", "您已驗證訂單 {orderId} 的實體庫存？\n\n點擊「是」將標記為就緒並直接發送至物流安排送貨。" },
                    { "InventoryForm_VerifyStockDispatch", "驗證庫存 & 出貨" },
                    { "InventoryForm_RestockApproval", "補貨申請審批流程" },
                    { "InventoryForm_ThreeLevelApproval", "三級審批：店長 → 庫存經理 → 採購部門" },
                    { "InventoryForm_FilterLocation", "按據點篩選：" },
                    { "InventoryForm_Refresh", "重新整理" },
                    { "InventoryForm_Approve", "核准（下一級）" },
                    { "InventoryForm_Reject", "拒絕申請" },
                    { "InventoryForm_SelectRequest", "請選擇一個補貨申請來核准。" },
                    { "InventoryForm_SelectReject", "請選擇一個補貨申請來拒絕。" },
                    { "InventoryForm_CannotApprove", "此申請狀態為「{status}」，無法進一步核准。" },
                    { "InventoryForm_CannotReject", "此申請狀態為「{status}」，無法拒絕。" },
                    { "InventoryForm_ConfirmApprove", "以 {role} 身分核准補貨申請 #{restockId}？\n\n這將推進審批至下一級。" },
                    { "InventoryForm_ConfirmReject", "拒絕補貨申請 #{restockId}？\n\n這將永久拒絕此申請。" },
                    { "InventoryForm_StockMovements", "庫存流轉（入庫 & 出庫）" },
                    { "InventoryForm_StockMovementsDesc", "追蹤所有庫存流轉，用於審計軌跡及準確性驗證。" },
                    { "InventoryForm_FilterProduct", "按商品篩選：" },
                    { "InventoryForm_StockListRefreshed", "庫存列表已重新整理。" },
                    { "InventoryForm_PleaseFillItemIdQty", "請填寫商品編號及數量。" },
                    { "InventoryForm_PleaseValidQty", "數量必須是有效的正數。" },
                    { "InventoryForm_StockIncreased", "商品 {id} 的庫存增加了 {qty}！" },
                    { "InventoryForm_ProcurementListRefreshed", "採購列表已重新整理。" },
                    { "InventoryForm_PleaseSelectSupplierItem", "請選擇供應商及物料項目。" },
                    { "InventoryForm_PleaseValidEstCost", "預估成本必須是有效的正數。" },
                    { "InventoryForm_ProcurementCreated", "採購單建立成功！" },
                    { "InventoryForm_SelectProcurementCancel", "請選擇一個採購單來取消。" },
                    { "InventoryForm_AlreadyCanceled", "此訂單已取消！" },
                    { "InventoryForm_ConfirmCancelProcurement", "確定要取消採購單 {procId} 嗎？" },
                    { "InventoryForm_ProcurementCanceled", "採購單 {procId} 已取消。" },
                    { "InventoryForm_SelectProcurementEdit", "請選擇一個採購單來編輯。" },
                    { "InventoryForm_EditMode", "進入採購單 {procId} 的編輯模式。\n\n（系統備註：完整的編輯介面排定於下一次更新。）" },
                    { "InventoryForm_SelectProcurementUpdate", "請選擇一個採購單來更新狀態。" },
                    { "InventoryForm_WaitApproval", "此訂單仍在「待處理」狀態。您必須等待財務部門核准後才能下單。" },
                    { "InventoryForm_AlreadyReceived", "此訂單已「收貨」並完成。" },
                    { "InventoryForm_AdvanceProcurement", "推進採購單 {procId}\n\n從：[{currentStatus}]\n到：[{nextStatus}]？" },
                    { "InventoryForm_ConfirmProgress", "確認進度" },
                    { "InventoryForm_ProcurementAdvanced", "採購單 {procId} 已推進至「{nextStatus}」。" },
                    { "InventoryForm_QuotationRefreshed", "報價單列表已重新整理。" },
                    { "InventoryForm_QuotationPrinted", "報價單列印成功！" },
                    { "InventoryForm_OrderSentLogistics", "訂單 {orderId} 已包裝並發送至物流！" },
                    { "InventoryForm_LowStockCheckComplete", "低庫存檢查完成！已自動產生補貨申請！" },
                    { "InventoryForm_OutwardRecorded", "出庫記錄：商品 {id}，數量 {qty}，從 {loc}！" },
                    { "PurchaseForm_Title", "採購管理" },
                    { "PurchaseForm_Tab_Orders", "採購單" },
                    { "PurchaseForm_Tab_Suppliers", "供應商" },
                    { "PurchaseForm_Tab_Products", "商品" },
                    { "PurchaseForm_CreatePO", "建立採購單" },
                    { "PurchaseForm_ApprovePO", "核准採購單" },
                    { "PurchaseForm_CancelPO", "取消採購單" },
                    { "PurchaseForm_PrintPO", "列印採購單" },
                    { "PurchaseForm_Refresh", "重新整理" },
                    { "PurchaseForm_PO_ID", "採購單編號" },
                    { "PurchaseForm_Supplier", "供應商" },
                    { "PurchaseForm_TotalAmount", "總金額" },
                    { "PurchaseForm_Status", "狀態" },
                    { "PurchaseForm_Date", "日期" },
                    { "PurchaseForm_CreatedBy", "建立者" },
                    { "PurchaseForm_Notes", "備註" },
                    { "PurchaseForm_Product_ID", "商品編號" },
                    { "PurchaseForm_Product_Name", "商品名稱" },
                    { "PurchaseForm_Quantity", "數量" },
                    { "PurchaseForm_UnitPrice", "單價" },
                    { "PurchaseForm_LineTotal", "小計" },
                    { "PurchaseForm_PleaseSelectPO", "請先選擇一個採購單。" },
                    { "PurchaseForm_CreatedSuccess", "採購單建立成功！" },
                    { "PurchaseForm_ApprovedSuccess", "採購單核准成功！" },
                    { "PurchaseForm_CancelledSuccess", "採購單取消成功！" },
                    { "PurchaseForm_Status_PendingAccounting", "送交會計部審批" },
                    { "PurchaseForm_Status_PendingApproval", "待核准" },
                    { "PurchaseForm_Status_Approved", "核准通過" },
                    { "PurchaseForm_Status_SentToSupplier", "已發送給供應商" },
                    { "PurchaseForm_Status_Received", "已收貨" },
                    { "PurchaseForm_Status_Cancelled", "已取消" },
                    { "MasterDataForm_Title", "主檔管理" },
                    { "MasterDataForm_Tab_Staff", "員工" },
                    { "MasterDataForm_Tab_Suppliers", "供應商" },
                    { "MasterDataForm_Tab_Customers", "客戶" },
                    { "MasterDataForm_Tab_Drivers", "司機" },
                    { "MasterDataForm_Tab_Products", "商品" },
                    { "MasterDataForm_Add", "新增" },
                    { "MasterDataForm_Edit", "編輯" },
                    { "MasterDataForm_Delete", "刪除" },
                    { "MasterDataForm_Refresh", "重新整理" },
                    { "MasterDataForm_ExportPDF", "匯出PDF" },
                    { "MasterDataForm_SupplierID", "供應商編號" },
                    { "MasterDataForm_SupplierName", "公司名稱" },
                    { "MasterDataForm_ContactPerson", "聯絡人" },
                    { "MasterDataForm_ContactNumber", "聯絡電話" },
                    { "MasterDataForm_Address", "地址" },
                    { "MasterDataForm_SupplierStatus", "狀態" },
                    { "MasterDataForm_ProductID", "商品編號" },
                    { "MasterDataForm_ProductName", "商品名稱" },
                    { "MasterDataForm_Category", "類別" },
                    { "MasterDataForm_UnitPrice", "售價" },
                    { "MasterDataForm_PurchasePrice", "進貨價" },
                    { "MasterDataForm_Description", "描述" },
                    { "MasterDataForm_ProductStatus", "狀態" },
                    { "MasterDataForm_PleaseFillDetails", "請填寫所有必填資訊。" },
                    { "MasterDataForm_SupplierAdded", "供應商新增成功！" },
                    { "MasterDataForm_SupplierUpdated", "供應商更新成功！" },
                    { "MasterDataForm_SupplierDeleted", "供應商刪除成功！" },
                    { "MasterDataForm_ProductAdded", "商品新增成功！" },
                    { "MasterDataForm_ProductUpdated", "商品更新成功！" },
                    { "MasterDataForm_ProductDeleted", "商品刪除成功！" },
                    { "MasterDataForm_ConfirmDelete", "確定要刪除此項目嗎？" },
                    { "LogisticForm_Title", "物流配送與技術派工排程" },
                    { "LogisticForm_Tab_Pending", "待配送" },
                    { "LogisticForm_Tab_Scheduling", "調度看板" },
                    { "LogisticForm_Tab_Tracking", "貨物追蹤" },
                    { "LogisticForm_Filter_Today", "今日" },
                    { "LogisticForm_Filter_Tomorrow", "明日" },
                    { "LogisticForm_Filter_Custom", "自訂日期" },
                    { "LogisticForm_Unassigned_List", "未分配任務清單" },
                    { "LogisticForm_Assign_Team", "指派團隊" },
                    { "LogisticForm_Team_Workload", "團隊工作量" },
                    { "LogisticForm_Select_Delivery", "請選擇要指派的配送任務。" },
                    { "LogisticForm_Select_Team", "請選擇要指派的團隊。" },
                    { "LogisticForm_Assign_Success", "{count} 個配送任務已成功指派給 {team}！" },
                    { "LogisticForm_Refresh", "重新整理" },
                    { "LogisticForm_Delivery_ID", "配送編號" },
                    { "LogisticForm_Order_Ref", "訂單編號" },
                    { "LogisticForm_Customer", "客戶" },
                    { "LogisticForm_Phone", "聯絡電話" },
                    { "LogisticForm_Address", "配送地址" },
                    { "LogisticForm_Volume", "商品體積" },
                    { "LogisticForm_Installation", "安裝需求" },
                    { "LogisticForm_Assigned_Team", "已指派團隊" },
                    { "LogisticForm_Scheduled_Date", "預約日期" },
                    { "LogisticForm_Created_On", "建立日期" },
                    { "LogisticForm_Team_ID", "團隊編號" },
                    { "LogisticForm_Team_Name", "團隊名稱" },
                    { "LogisticForm_Team_Type", "團隊類型" },
                    { "LogisticForm_Members", "成員數" },
                    { "LogisticForm_Time_Slot", "時段" },
                    { "LogisticForm_Status", "狀態" },
                    { "HRForm_Title", "人事組織與權限管理" },
                    { "HRForm_Tab_Staff", "職員總表" },
                    { "HRForm_Tab_Roles", "權限設定" },
                    { "HRForm_Add_Staff", "新增員工" },
                    { "HRForm_Update_Staff", "更新員工檔案" },
                    { "HRForm_Search_Placeholder", "依員工編號、姓名或部門搜尋..." },
                    { "HRForm_Department", "部門" },
                    { "HRForm_Job_Title", "職稱" },
                    { "HRForm_Location", "據點派任" },
                    { "HRForm_Role", "系統角色" },
                    { "HRForm_Phone", "連絡電話" },
                    { "HRForm_Email", "電子郵件" },
                    { "HRForm_Hire_Date", "到職日" },
                    { "HRForm_Staff_Status", "員工狀態" },
                    { "HRForm_Password", "密碼" },
                    { "HRForm_Confirm_Password", "確認密碼" },
                    { "HRForm_New_Password", "新密碼" },
                    { "HRForm_Password_Strength", "密碼強度" },
                    { "HRForm_Password_Invalid", "密碼不符合安全性要求" },
                    { "HRForm_Passwords_Do_Not_Match", "兩次輸入的密碼不相同" },
                    { "HRForm_Select_Department_First", "請先選擇部門" },
                    { "HRForm_Location_Required", "請派任員工至具體據點（門市、倉庫或團隊）" },
                    { "HRForm_Staff_Added", "員工新增成功！" },
                    { "HRForm_Staff_Updated", "員工檔案更新成功！" },
                    { "HRForm_Staff_Deleted", "員工刪除成功！" },
                    { "HRForm_Confirm_Delete", "確定要刪除此員工嗎？" },
                    { "HRForm_Select_Staff", "請選擇一位員工" },
                    { "HRForm_Staff_ID", "員工編號" },
                    { "HRForm_Staff_Name", "員工姓名" },
                    { "Dashboard_Title", "決策儀表板" },
                    { "Dashboard_TotalOrders", "訂單總數" },
                    { "Dashboard_TotalSoldItems", "總銷量" },
                    { "Dashboard_TotalRevenue", "總收入" },
                    { "Dashboard_TotalGrossProfit", "總毛利" },
                    { "Dashboard_7DayTrend", "7日訂單趨勢" },
                    { "Dashboard_TopSellingProducts", "熱銷商品" },
                    { "Dashboard_CurrentMonth", "本月" },
                    { "HRForm_Department_Admin", "管理部" },
                    { "HRForm_Department_Sales", "銷售部" },
                    { "HRForm_Department_Tech", "技術部" },
                    { "HRForm_Department_Logistics", "物流部" },
                    { "HRForm_Department_Warehouse", "倉庫管理部" },
                    { "HRForm_Location_HQ", "總部" },
                    { "HRForm_Location_Retail_Shop", "零售門市" },
                    { "HRForm_Location_Warehouse", "倉庫" },
                    { "HRForm_Location_Delivery_Team", "配送隊" },
                    { "HRForm_Location_Tech_Team", "技術團隊" },
                    { "HRForm_Role_Admin", "管理員" },
                    { "HRForm_Role_Manager", "經理" },
                    { "HRForm_Role_Staff", "一般員工" },
                    { "HRForm_Status_Active", "在職" },
                    { "HRForm_Status_Inactive", "離職" },
                    { "MessageForm_Title", "系統信箱" },
                    { "MessageForm_Tab_Inbox", "收件箱" },
                    { "MessageForm_Tab_Outbox", "已發送" },
                    { "MessageForm_Btn_Unread_Filter", "顯示未讀" },
                    { "MessageForm_Btn_Show_All", "顯示全部" },
                    { "MessageForm_Btn_Send_Message", "發送訊息" },
                    { "MessageForm_Btn_Refresh", "重新整理" },
                    { "MessageForm_Btn_Mark_Read", "標記已讀" },
                    { "MessageForm_Btn_Delete", "刪除" },
                    { "MessageForm_Btn_Reply", "回覆" },
                    { "MessageForm_Lbl_Recipient", "收件人：" },
                    { "MessageForm_Lbl_Subject", "主旨：" },
                    { "MessageForm_Lbl_Content", "內容：" },
                    { "MessageForm_Please_Fill_All", "請填寫完整資訊！" },
                    { "MessageForm_Message_Sent", "訊息已發送！" },
                    { "MessageForm_Confirm_Delete", "確定要刪除這條訊息嗎？" },
                    { "NotificationForm_Title", "系統通知" },
                    { "NotificationForm_Btn_Unread_Filter", "顯示未讀" },
                    { "NotificationForm_Btn_Show_All", "顯示全部" },
                    { "NotificationForm_Btn_Refresh", "重新整理" },
                    { "NotificationForm_Btn_Mark_All_Read", "標記全部已讀" },
                    { "NotificationForm_Btn_Clear_All", "清空全部" },
                    { "NotificationForm_Btn_Test_Notification", "測試彈窗" },
                    { "NotificationForm_All_Marked_Read", "全部已標記為已讀！" },
                    { "NotificationForm_Confirm_Clear_All", "確定要清空所有通知嗎？" },
                    { "NotificationForm_Test_Title", "測試通知" },
                    { "NotificationForm_Test_Message", "這是一個 Windows 氣泡通知的測試！" },
                    { "NotificationType_New_Message", "新訊息" },
                    { "NotificationType_Restock_Approval", "補貨申請" },
                    { "NotificationType_Purchase_Approval", "採購申請" },
                    { "NotificationType_System_Alert", "系統警示" },
                    { "NotificationType_Urgent_Task", "緊急任務" },
                    { "MainForm_Logout", "登出" },
                    { "MainForm_LogoutConfirm", "確定要登出嗎？" },
                    { "MainForm_LogoutConfirmTitle", "確認登出" }
                }
            }
        };

        public static string GetString(string key)
        {
            if (Resources.TryGetValue(_currentLanguage, out var language))
            {
                if (language.TryGetValue(key, out var value))
                {
                    return value;
                }
            }
            return key;
        }

        public static void ToggleLanguage()
        {
            CurrentLanguage = _currentLanguage == "en" ? "zh-TW" : "en";
        }
    }
}
